---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(tidyverse))
```

```{r}
design <- "/mnt/beegfs/userdata/h_herrmann/design/gr1234/baseline_curated_design_gr1234.tsv"
tumor_only <- "/mnt/beegfs/userdata/h_herrmann/mela_ici_response_results/analyze_wes/gr1234/tumor_only/tmb/tmb.tsv"
normal_tumor <- "/mnt/beegfs/userdata/h_herrmann/mela_ici_response_results/analyze_wes/gr1234/normal_tumor/tmb/tmb.tsv"
out_dir <- "/mnt/beegfs/userdata/h_herrmann/mela_ici_response_results/analyze_wes/gr1234/"
```

```{r}
design <- read_tsv(design, show_col_types = FALSE)

tumor_only <- read_tsv(tumor_only, show_col_types = FALSE) %>%
   rename(TMB_tumor_only = "TMB")
normal_tumor <- read_tsv(normal_tumor, show_col_types = FALSE) %>%
   rename(TMB_normal_tumor = "TMB")
```

# Corrective factor 
```{r}
factor <- mean(tumor_only$TMB_tumor_only) / mean(normal_tumor$TMB_normal_tumor)
normal_tumor <- normal_tumor %>% mutate(Ajusted_TMB_normal_tumor = TMB_normal_tumor * factor)

both_tmb <- inner_join(tumor_only, normal_tumor, by = c("Sample_ID_rna" = "Sample_ID"))

ggplot(both_tmb, aes(TMB_normal_tumor, TMB_tumor_only)) +
   geom_point() +
   geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
   geom_abline(slope = 1, linetype = "dashed") +
   lims(x = c(0, 20), y = c(0, 20)) +
   theme_classic() +
   theme(axis.text.x = element_text(size = 18, color = "black"),
         axis.text.y = element_text(size = 18, color = "black"),
         text = element_text(size = 18, color = "black"),
         strip.text = element_text(size = 18, color = "black"),
         legend.position = "bottom") +
   labs(x = "Non-synonymous\ncoding mutation / Mb\nNormal-tumor", y = "Non-synonymous\ncoding mutation / Mb\nTumor only")

ggplot(both_tmb, aes(Ajusted_TMB_normal_tumor, TMB_tumor_only)) +
   geom_point() +
   geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
   geom_abline(slope = 1, linetype = "dashed") +
   lims(x = c(0, 40), y = c(0, 40)) +
   theme_classic() +
   theme(axis.text.x = element_text(size = 18, color = "black"),
         axis.text.y = element_text(size = 18, color = "black"),
         text = element_text(size = 18, color = "black"),
         strip.text = element_text(size = 18, color = "black"),
         legend.position = "bottom") +
   labs(x = "Non-synonymous\ncoding mutation / Mb\nNormal-tumor", y = "Non-synonymous\ncoding mutation / Mb\nAjusted tumor only")
```

# Project on linear regression
```{r}
linear <- lm(TMB_tumor_only ~ Ajusted_TMB_normal_tumor, data = both_tmb)

linear_tmb_normal_tumor <- as.data.frame(predict.lm(linear, newdata = normal_tumor)) %>%
   mutate(Sample_ID = normal_tumor$Sample_ID) %>%
   rename(Linear_TMB_normal_tumor = "predict.lm(linear, newdata = normal_tumor)") %>%
   inner_join(normal_tumor, ., by = "Sample_ID")

ggplot(linear_tmb_normal_tumor, aes(TMB_normal_tumor, Linear_TMB_normal_tumor)) +
   geom_point() +
   geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
   geom_abline(slope = 1, linetype = "dashed") +
   lims(x = c(0, 20), y = c(0, 20)) +
   theme_classic() +
   theme(axis.text.x = element_text(size = 18, color = "black"),
         axis.text.y = element_text(size = 18, color = "black"),
         text = element_text(size = 18, color = "black"),
         strip.text = element_text(size = 18, color = "black"),
         legend.position = "bottom") +
   labs(x = "Non-synonymous\ncoding mutation / Mb\nNormal-tumor", y = "Non-synonymous\ncoding mutation / Mb\nLinear tumor only")
```

```{r}
all_tmb <- full_join(tumor_only, normal_tumor, by = c("Sample_ID_rna" = "Sample_ID")) %>%
   mutate(TMB = if_else(is.na(TMB_tumor_only), Ajusted_TMB_normal_tumor, TMB_tumor_only)) %>%
   inner_join(., design, by = c("Sample_ID_rna" = "Sample_ID"))

ggplot(all_tmb, aes(Response, TMB, fill = Response)) +
   geom_boxplot() +
   scale_fill_manual(values = c("R" = "#56B4E9", "NR" = "#FF9999")) +
   theme_classic() +
   stat_compare_means(method = "wilcox.test", label.x = 1.1, vjust = 0.5, label = "p.format", size = 6.5) +
   theme(axis.text.x = element_text(size = 18, color = "black"),
         axis.text.y = element_text(size = 18, color = "black"),
         text = element_text(size = 18, color = "black"),
         strip.text = element_text(size = 18, color = "black"),
         legend.position = "bottom") +
   guides(fill = "none") +
   labs(x = "", y = "Non-synonymous\ncoding mutation / Mb\nTumor only + (ajusted) normal-tumor")

all_tmb2 <- full_join(tumor_only, linear_tmb_normal_tumor, by = c("Sample_ID_rna" = "Sample_ID")) %>%
   mutate(TMB = if_else(is.na(TMB_tumor_only), Linear_TMB_normal_tumor, TMB_tumor_only)) %>%
   inner_join(., design, by = c("Sample_ID_rna" = "Sample_ID"))

ggplot(all_tmb2, aes(Response, TMB, fill = Response)) +
   geom_boxplot() +
   scale_fill_manual(values = c("R" = "#56B4E9", "NR" = "#FF9999")) +
   theme_classic() +
   stat_compare_means(method = "wilcox.test", label.x = 1.1, vjust = 0.5, label = "p.format", size = 6.5) +
   theme(axis.text.x = element_text(size = 18, color = "black"),
         axis.text.y = element_text(size = 18, color = "black"),
         text = element_text(size = 18, color = "black"),
         strip.text = element_text(size = 18, color = "black"),
         legend.position = "bottom") +
   guides(fill = "none") +
   labs(x = "", y = "Non-synonymous\ncoding mutation / Mb\nTumor only + (linear) normal-tumor")
```

